spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
      - classpath:db/data
  datasource:
    writer:
      driver-class-name: org.postgresql.Driver
      read-only: false
      jdbc-url: jdbc:postgresql://localhost:5432/igoparking
      username: postgres
      password: postgres
      pool-name: HikariCP-Writer
    reader:
      driver-class-name: org.postgresql.Driver
      read-only: true
      jdbc-url: jdbc:postgresql://localhost:5432/igoparking
      username: postgres
      password: postgres
      pool-name: HikariCP-Reader
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

