# if you want to use independent config,
# exclude config profile and redefine properties here
spring:
    profiles:
        include:
#            - usecase-api
            - mcp-client-adapter-in


logging.level.org.springframework.ai: DEBUG

server.port: 8080
