version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: igoparking
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata:
