# if you want to use independent config,
# exclude config profile and redefine properties here
spring:
  profiles:
    include:
      - usecase-api
      - rds-adapter-out


    ai:
        mcp:
            server:
                name: person-mcp-server
                version: 1.0.0
    jpa:
        database-platform: H2
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop

logging.level.org.springframework.ai: DEBUG

server.port: 8060
