CREATE TABLE social_login_account
(
    social_login_account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by              VARCHAR(255),
    created_at              TIMESTAMP,
    modified_by             VARCHAR(255),
    modified_at             TIMESTAMP,
    email                   VARCHAR(255)                            NOT NULL,
    name                    VARCHAR(255)                            NOT NULL,
    profile_image_url       VARCHAR(255),
    status                  VARCHAR(255)                            NOT NULL,
    PRIMARY KEY (social_login_account_id)
);

CREATE INDEX idx_email ON social_login_account (email);

COMMENT
    ON TABLE social_login_account IS '소셜 로그인 계정';
COMMENT
    ON COLUMN social_login_account.email IS '소셜 로그인 메일 주소';
COMMENT
    ON COLUMN social_login_account.name IS '소셜 로그인 서비스에 등록된 이름';
COMMENT
    ON COLUMN social_login_account.profile_image_url IS '소셜 로그인에 등록된 프로필 이미지 URL';
COMMENT
    ON COLUMN social_login_account.status IS '계정 상태';
