CREATE TABLE content
(
    content_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by  VARCHAR(255),
    created_at  TIMESTAMP,
    modified_by VARCHAR(255),
    modified_at TIMESTAMP,
    liked_count BIGINT                                  NOT NULL DEFAULT 0,
    PRIMARY KEY (content_id)
);


COMMENT
    ON TABLE content IS '콘텐츠';
COMMENT
    ON COLUMN content.content_id IS '콘텐츠 id';
COMMENT
    ON COLUMN content.liked_count IS '콘텐츠 총 좋아요 수';
